src/main/java/nl/sogeti/demo/model/Person.java
package nl.sogeti.demo.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Person implements Serializable{

	private static final long serialVersionUID = 982374691237864L;

	@Id
	@GeneratedValue
	private Long id;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	private String name;

}

src/main/java/nl/sogeti/demo/controller/PersonBean.java
package nl.sogeti.demo.controller;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.inject.Inject;

import nl.sogeti.demo.common.Parameters;
import nl.sogeti.demo.model.Person;
import nl.sogeti.demo.service.PersonService;

@ManagedBean
@SessionScoped
public class PersonBean implements Serializable {
 
	private static final long serialVersionUID = 1L;
	
	@Inject
	Logger logger;
	
	@Inject
	PersonService personService;
 
	private String name;
 
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	public List<Person> list(){
		return personService.findAll();
	}
	
	public String getTestParameter(){
		return Parameters.TEST.getValue();
	}
	
	public String save(){
		if(name != null){
			Person person = new Person();
			person.setName(this.name);
			personService.save(person);
			logger.info("Person saved");
		}
		
		return "hello";
	}
}

src/main/webapp/hello.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>JSF 2.0 Hello World</title>
</h:head>
<h:body>
	<h3>JSF 2.0 Hello World Example - hello.xhtml</h3>
	<h:form>
		<h:outputText value ="Parameter: #{personBean.testParameter}" /><br></br>
		<h:inputText value="#{personBean.name}"></h:inputText>
		<h:commandButton value="save" action="#{personBean.save}"></h:commandButton>
	</h:form>
	<br></br>
	<h:dataTable id="personTable" var="person" value="#{personBean.list()}">
		<h:column>
			<f:facet name="header">
				<h:outputText value="Name" />
			</f:facet>
			<h:panelGrid rendered="#{not empty person.name}">
				<h:outputText
					value="#{person.name}" />
			</h:panelGrid>
		</h:column>
	</h:dataTable>
</h:body>
</html>

src/main/webapp/index.jsp
<html>
<body>
<h2>Hello World!</h2>
</body>
</html>

src/main/webapp/welcome.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"    
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:head>
    	<title>JSF 2.0 Hello World</title>
    </h:head>
    <h:body bgcolor="white">
    	<h3>JSF 2.0 Hello World Example - welcome.xhtml</h3>
    	<h4>Welcome #{helloBean.name}</h4>
    </h:body>
</html>